### ISSUE TITLE
Question about building the robot

### ISSUE THREAD

**Issue by dgerod** [mstoelen/GummiArm#1]
I am interested in the robot and I think that is cool that you share the CAD of the pieces. However, after seeing your videos and looking in this repository I think that more information is needed to build it, for example how to assemble the pieces and how to program the controller. Are you thinking on sharing this information too?

Could I use the robot for personal proposes? My interest is not in building robots but in AI and Robotics and I need something for my personal research in this area.  
How many time do you think I will need to build it? And how much it will cost approximately?

Thanks in advance.

**Comment by mstoelen** [comment]
Hi, you can certainly use the project for personal (and/or professional) purposes. Please also feel free to contribute!

We are working on a Wiki for documenting the parts needed (beyond the printables), the build process (any help appreciated), the costs associated, and how to install/run the code. For the current 7+1 DOF version (v2.1) the total cost is approaching $5000, mainly due to the beefy MX-106T Dynamixel servos in the shoulder (need an alternative). 

Total build time would be great to find out about, not sure. The parts require around 500 grams of PLA in total, likely a week of printing on a typical hobby-grade 3D printer. No soldering is required. Btw, the basic ROS-based controllers are available in the 'orchestration' folder.

Hope this helps, and keep in touch. Happy to support if you decide to build.

**Comment by dgerod** [comment]
Thanks for your answer!

The price should not be a problem so I am still interested on it :-). 

However, I have an important question, are you using it to do Learning by Demonstration? 
In my research work I have to teach the robot by hand to pick objects, do you think that your robot is feasible for doing this task? The trajectories will be executed in joint space and not in Cartesian space.

**Comment by mstoelen** [comment]
Hi, yes that type of learning is one potential application. Right now you can teleoperate the arm (we use a £100 space navigator joystick), and record joint angles or Cartesian pose. Also working on kinesthetic teaching, through force sensing in joints, but still work in progress.

**Comment by dgerod** [comment]
Good to know, I am really interesting on the kinesthetic teaching as it is one of my essential requirements for the robot.

When you have the wiki ready, or a preliminary version, I will take a look to understand better what is needed to build the robot. Please, let me know when it is ready, thanks.

**Comment by mstoelen** [comment]
A preliminary version of the wiki is now up, check it out here: https://github.com/mstoelen/GummiArm/wiki

**Comment by mstoelen** [comment]
Hi, just to let you know that we are working on detailed build instructions right now. See progress [here](http://htmlpreview.github.com/?https://github.com/mstoelen/GummiArm/blob/master/media/instructions/build.html).

**Comment by dgerod** [comment]
Thanks for sharing!
I would like to follow the process... but the link is not working ;-)

**Comment by mstoelen** [comment]
Strange, it opens fine in my browser (Safari). What browser are you using?
You can also clone the repository, then open this html file on your computer: [https://github.com/mstoelen/GummiArm/blob/master/media/instructions/build.html](https://github.com/mstoelen/GummiArm/blob/master/media/instructions/build.html)

**Comment by dgerod** [comment]
I use Firefox but it was a problem in the configuration of my browser, sorry. I should had tried another browser (i.e. Chrome) to check the link.

I will study the process during the week end as I would like to understand it well. However, I have just done a quick check and it seems very good. Thanks again for sharing.
